name: dart_secure
description: A Dart package that provides functionalities to enhance the security of Dart applications; integration of multiple cybersecurity practices to secure user interactions.
version: 2.0.0
homepage: https://github.com/Syf-Almjd/dart_secure

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  local_auth: ^3.0.1
  encrypt: ^5.0.3
  firebase_auth: ^6.5.3
  firebase_core: ^4.11.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
