name: dart_secure
description: A Dart package that provides functionalities to enhance the security of Dart applications; integration of multiple cybersecurity practices to secure user interactions.
version: 0.4.2
homepage: https://github.com/Syf-Almjd/dart_secure

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  encrypt: ^5.0.1
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
